MEMORY
{
  RAM : ORIGIN = 0x50000000, LENGTH = 16K
  FLASH : ORIGIN = 0x00000000, LENGTH = 16M
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", RAM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);

PROVIDE(_interrupt0 = DefaultInterruptHandler);
PROVIDE(_interrupt1 = DefaultInterruptHandler);
PROVIDE(_interrupt2 = DefaultInterruptHandler);
PROVIDE(_interrupt3 = DefaultInterruptHandler);
